### ISSUE TITLE
为什么我在VS Code里面debug一直报错

### ISSUE THREAD

**Issue by jimwan** [jaggerwang/jw-flutter-demo#1]
WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:
        export LANG=en_US.UTF-8

我是在mac上开发的，我已经加过export LANG=en_US.UTF-8 到~/.bash_profile里面了，还是一样的

**Comment by jaggerwang** [comment]
重启终端后执行`env | grep LANG` 命令查看修改是否已生效，如果已生效但 VSCode 还不行再重启 VSCode 试试。

**Comment by jimwan** [comment]
非常感谢这么快的回复，我按照错误提示修改后可以了。
最重要的是VSCode要重启，谢谢
